### ISSUE TITLE
Problem in model with input parameters

### ISSUE THREAD

**Issue by rcabanasdepaz** [PGM-Lab/InferPy#116]
In the following code:

```
@models.probmodel
def pca(k,d):
    w = models.Normal(np.zeros([k,d]), 1, name="w")

    with models.datamodel():
        z = models.Normal(np.zeros(k), 1)
        x = models.Normal(tf.matmul(z,w), 1)

k, d = 5, 10
m = pca(k,d)

```

I get:

```
Traceback (most recent call last):
  File "/Users/rcabanas/venv/BBVI-TFP/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-26-6d27310c98a5>", line 1, in <module>
    m = pca(k,d)
  File "/Users/rcabanas/GoogleDrive/UAL/inferpy/repo/InferPy/inferpy1/inferpy/models/prob_model.py", line 98, in wrapper
    builder=builder
  File "/Users/rcabanas/GoogleDrive/UAL/inferpy/repo/InferPy/inferpy1/inferpy/models/prob_model.py", line 115, in __init__
    nx_graph, model_vars = self._build_model()
  File "/Users/rcabanas/GoogleDrive/UAL/inferpy/repo/InferPy/inferpy1/inferpy/models/prob_model.py", line 126, in _build_model
    self.builder()
TypeError: pca() missing 2 required positional arguments: 'k' and 'd'
```

**Comment by jcozar87** [comment]
fixed in 2789909e8bbb2ade0d26e020fcd49a14f56c95c

In addition, note that inside probmodel definitions you always have to use names for random variables:
```python
from inferpy import models

@models.probmodel
def pca(k,d):
    w = models.Normal(np.zeros([k,d]), 1, name="w")

    with models.datamodel():
        z = models.Normal(np.zeros(k), 1, name='z')
        x = models.Normal(tf.matmul(z,w), 1, name='x')

k, d = 5, 10
m = pca(k,d)
```
