### ISSUE TITLE
ValueError in Bernoulli

### ISSUE THREAD

**Issue by rcabanasdepaz** [PGM-Lab/InferPy#149]
The following code:

```
@inf.probmodel
def log_reg(d):
    w0 = inf.Normal(0., 1, name="w0")
    w = inf.Normal(0., 1, batch_shape=[d], name="w")

    with inf.datamodel():
        x = inf.Normal(0., 2., batch_shape=d, name="x")
        y = inf.Bernoulli(logits = w0 + x @ tf.transpose(w), name="y")


m = log_reg(d=2)

```

raises

```
Traceback (most recent call last):
  File "/Users/rcabanas/venv/InferPy/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-17cfb595e392>", line 1, in <module>
    inf.Bernoulli(logits = w0 + x @ tf.transpose(w), name="y")
  File "/Users/rcabanas/GoogleDrive/UAL/inferpy/repo/InferPy/inferpy/models/random_variable.py", line 401, in func
    ed_random_var = _make_edward_random_variable(tfp_dist)(sample_shape=sample_shape, name=rv_name)
  File "/Users/rcabanas/venv/InferPy/lib/python3.6/site-packages/tensorflow_probability/python/edward2/interceptor.py", line 193, in func_wrapped
    return interceptor(func, *args, **kwargs)
  File "/Users/rcabanas/GoogleDrive/UAL/inferpy/repo/InferPy/inferpy/util/interceptor.py", line 33, in interceptor
    lambda: _value
  File "/Users/rcabanas/venv/InferPy/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/Users/rcabanas/venv/InferPy/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2147, in cond
    (val_x.dtype.name, val_y.dtype.name))
ValueError: Outputs of true_fn and false_fn must have the same type: float32, int32
```

**Comment by jcozar87** [comment]
The problem here is that `tf.cond` needs to use the same dtype for _if_ and _else_ functions. The actual code uses the simplest initial value for the variable `observed_value_var`, equals to tf.zeros. The dtype of `tf.zeros` is `float32`, but there are Random Variables which uses other types, as Bernoulli which uses `int32`. We need a mapping of, at least, dtypes for eah Random Variable type.
