### ISSUE TITLE
BUG: compatibility issue with TF 1.14.0

### ISSUE THREAD

**Issue by rcabanasdepaz** [PGM-Lab/InferPy#167]
When I try to import the package:

```
import inferpy as inf
```
I get this error:

```
Traceback (most recent call last):
  File "/Users/rcabanas/venv/InferPy/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-db62ddd3a029>", line 1, in <module>
    import inferpy as inf

[ . . . ]

"/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "...../InferPy/lib/python3.6/site-packages/tensorflow_probability/python/distributions/linear_gaussian_ssm.py", line 41, in <module>
    _matmul = linear_operator_util.matmul_with_broadcast
AttributeError: module 'tensorflow.python.ops.linalg.linear_operator_util' has no attribute 'matmul_with_broadcast'

```

It seems to be a compatibility issue with Tensorflow 1.14. The installed packages are:

tensorflow==1.14.0
tensorflow-estimator==1.14.0
tensorflow-probability==0.6.0

**Comment by jcozar87** [comment]
It seems that the problem is related to a `tensorflow-probability==0.6.0` compatibility with `tensorflow==1.14.0` (or `tensorflow-estimator==1.14.0`).

This problem does not happen with `tensorflow-probability==0.7.0`.
