### ISSUE TITLE
Categorical dimension bug

### ISSUE THREAD

**Issue by rcabanasdepaz** [PGM-Lab/InferPy#30]
```
t = inf.models.Normal(loc = [0.1, 0.4, 0.6], scale= 0.06)

x = inf.models.Categorical(probs = [t, 1])

x.dim
```

raises:

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/rcabanas/Documents/UAL/inferpy/repo/InferPy/inferpy/models/random_variable.py", line 63, in dim
    return self.base_object.shape.as_list()[-1]
IndexError: list index out of range

**Comment by rcabanasdepaz** [comment]
With the new factory version, elements in a vectorial parameter must of shape no more than (1,1)

```

t = inf.models.Normal(loc = [0.1], scale= 0.06)

x = inf.models.Categorical(probs = [t, 1])

x.dim
```
