### ISSUE TITLE
NoneType error when sampling from exponential

### ISSUE THREAD

**Issue by rcabanasdepaz** [PGM-Lab/InferPy#68]
The following code

```
inf.models.Exponential(rate=[1]).sample()
```

raises this error:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/rcabanas/Documents/UAL/inferpy/repo/InferPy/inferpy/util/wrappers.py", line 32, in wrapper
    output_eval_vect = inf.util.Runtime.tf_sess.run(output_tf_vect)
  File "/Users/rcabanas/venv/2.7/inferpy2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/Users/rcabanas/venv/2.7/inferpy2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1113, in _run
    self._graph, fetches, feed_dict_tensor, feed_handles=feed_handles)
  File "/Users/rcabanas/venv/2.7/inferpy2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 420, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "/Users/rcabanas/venv/2.7/inferpy2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 240, in for_fetch
    return _ListFetchMapper(fetch)
  File "/Users/rcabanas/venv/2.7/inferpy2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 347, in __init__
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/Users/rcabanas/venv/2.7/inferpy2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 237, in for_fetch
    (fetch, type(fetch)))
TypeError: Fetch argument None has invalid type <type 'NoneType'>
``

**Comment by rcabanasdepaz** [comment]
Also affecting to Gamma and InverseGamma. Fixed
